angular.module('partials', [])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/debtclock.html', [
'<div ng-controller="DebtClock" class="treemap-root"><div id="debtclock-dashboard"><div id="debtclock-total-number">現有國債：<span id="debtclock_total">{{ total.debt | unitconvert }}</span></div><div id="debtclock-total-person">（平均每人負擔：<span id="debtclock_perperson">{{ total.avg | number:0 }}</span>元）</div></div></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/login.html', [
'<div id="login-holder" ng-model="loginShown" ng-controller="LoginController" ui-modal="ui-modal" class="modal fade"><a data-dismiss="modal" class="btn close">&times;</a><div class="modal-header"><h1>Login</h1></div><div class="modal-body"><div class="row-fluid"><div class="span6"><form ng-submit="submit()"><label>email</label><input type="text" ng-model="email" class="email login-inp"/><label>Password</label><input type="password" ng-model="password" class="password login-inp"/><div class="clear"></div><input type="submit" value="Login" class="btn btn-primary submit-login"/></form></div><div class="span6"><p>Login with:</p><a onclick="window.open(\'/auth/github\', \'auth\', \'height=400,width=400,modal=yes,alwaysRaised=yes\')" class="btn btn-primary login-github">Github</a><a onclick="window.open(\'/auth/twitter\', \'auth\', \'height=400,width=400,modal=yes,alwaysRaised=yes\')" class="btn btn-primary login-twitter">Twitter</a><a onclick="window.open(\'/auth/facebook\', \'auth\', \'height=400,width=400,modal=yes,alwaysRaised=yes\')" class="btn btn-primary login-facebook">facebook</a></div><div class="clearfix"></div><div ng-show="message" ng-model="message" class="alert alert-error">{{ message }}</div></div></div><div class="modal-footer"></div></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/nav.html', [
'<ul class="nav"><li ng-class="getClass(\'/view2\')"><a ng-href="/view2">每日支出</a></li><li ng-class="getClass(\'/view3\')"><a ng-href="/view3">鳥瞰圖</a></li><li ng-class="getClass(\'/view4\')"><a ng-href="/budget">變化圖</a></li><li ng-class="getClass(\'/debtclock\')"><a ng-href="/debtclock">國債鐘</a></li><li class="dropdown"><a id="dLabel" role="button" data-toggle="dropdown" data-target="#" class="dropdown-toggle">單位換算<b class="caret"></b></a><ul id="unit-selector" ng-controller="UnitMapper" role="menu" aria-labelledby="dLabel" class="dropdown-menu"><li ng-repeat="item in units"><a onclick="UnitMapper.update({{$index}})">{{item[1]}}</a></li><li class="divider"></li><li><a onclick="UnitMapper.update(-1)">隨便來一個</a></li><li class="disabled"><a data-toggle="modal" onclick="$(&quot;#addunit-value-group&quot;).removeClass(&quot;error&quot;);$(&quot;#addunit-modal&quot;).modal()">我要加單位</a></li></ul><div id="addunit-modal" role="dialog" tabindex="-1" aria-labelledby="budget-addunit-label" aria-hidden="true" class="modal fade"><div class="modal-header"><button type="button" data-dismiss="modal" aria-hidden="true" class="close">x</button><h3 id="budget-addunit-label">我要加單位</h3></div><div style="text-align:center" class="modal-body"><div class="input-append"><span class="add-on">一</span><input title="量詞欄位不可空白" ng-model="addunit_quantity" type="text" placeholder="量詞,如:個 或 塊" class="input-mini"/><input title="單位欄位不可空白" ng-model="addunit_unit" type="text" placeholder="單位,如:蘋果 或 金條" class="input-medium"/><span class="add-on">等於</span><input title="價錢欄位需填數字" ng-model="addunit_value" type="text" placeholder="價錢,如:50 或 2000 (全數字)" class="span2"/><span class="add-on">元</span></div><div id="budget-addunit-result">預覽: 一{{addunit_quantity}}{{addunit_unit}} 等於 {{addunit_value}} 元</div></div><div class="modal-footer"><button data-dismiss="modal" aria-hidden="true" class="btn">取消</button><button ng-click="addunit()" class="btn btn-primary">送出</button></div></div></li></ul><ul class="nav pull-right"><li ng-class="getClass(\'/profile\')"><a ng-href="/profile">我的帳號</a></li><li><a><div data-send="false" data-href="https://facebook.com/g0v.tw" data-width="120" data-layout="button_count" data-show-faces="false" data-font="verdana" class="fb-like"></div></a></li></ul>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial1.html', [
'<div ng-controller="MyCtrl1"><div id="categories" when-h-scrolled="updateblah()" class="categories"><div style="left:{{i*300+30}}px" ng-repeat="(i,result) in results" class="category"><button style="text-align:center;" class="btn">{{ result.name }}</button><ul when-scrolled="moreProducts(i)" ng-class="&quot;product&quot;+blah(i)" class="thumbnails products"><li ng-repeat="product in result.products" class="span3 product"><img src="img/htc-one.jpg"/><h3>{{ product.name }}</h3><p>{{ product.description }} qwertyuaisdfghjzkxcvbj</p></li></ul></div></div></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial2.html', [
'<div class="container"><div id="dailybread" ng-controller="DailyBread"><h2 class="page-header">每日支出<small>納稅人每日支付些什麼？</small></h2><div id="preloader" style="text-align: center; padding: 100px;"><span class="txt">loading</span></div><div id="content-wrap" style="display: none;"><div id="db-topbar" class="layout-row layout-3col-15-70-15"><form class="form-inline"><label>每年繳納稅金 : <div class="input-prepend input-append"><span class="add-on">$</span><input type="text" id="db-tax" name="db-tax" ng-model="tax" class="input-small"/><a ng-click="tax= tax + 5000" class="btn btn-primary">+</a><a ng-click="tax= tax - 5000" class="btn btn-danger">-</a></div></label></form></div></div></div></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial3.html', [
'<div id="treemap-root"><div id="treemap-root-inner"><div id="debitmask">2,500億</div></div><button id="treemap-backbtn" class="btn"><i class="icon-big-back"></i></button><div id="budget-detail"><div id="budget-detail-inner"><div id="budget-detail-info"><h3><i style="margin-top:2px" class="icon-big-info-sign"></i><span id="budget-detail-depname-field">教育部</span></h3><div id="budget-detail-amount"><div id="budget-detail-amount-field1"><span id="budget-detail-amount-field1-value">2,100億</span><span id="budget-detail-amount-field1-unit">元</span></div>&#x0028;即為<span id="budget-detail-amount-field2">2,100億元</span>)</div><div id="budget-detail-category">屬於<span id="budget-detail-category-field">教育支出</span>項目</div></div><hr/><div id="budget-tagger"><div class="input-append"><input ng-model="tagname" size="13" type="text" placeholder="例如: 林益世" class="span2"/><button type="button" ng-click="addtag()" class="btn">標記相關人士</button></div><div id="budget-tags"><span ng-repeat="tag in tags" class="badge budget-tag"> ',
'{{tag}}  </span></div></div><hr/><div id="budget-vote"><div id="budget-vote-label"><span class="label">透過按一下表達你對於此預算的看法！</span></div><div id="BudgetItem" class="btn-toolbar"><div class="btn-group"><button ng-click="like()" class="btn vote-btn"><span id="vote1">{{nlikes || 0}} 人</span><br/><i class="icon-big-plus"></i><br/>希望追加</button><button ng-click="confuse()" class="btn vote-btn"><span id="vote2">{{nconfuses || 0}} 人</span><br/><i class="icon-big-question-sign"> </i><br/>表示不懂</button><button ng-click="hate()" class="btn vote-btn"><span id="vote3">{{nhates || 0}} 人</span><br/><i class="icon-big-minus"></i><br/>建議減少</button><button ng-click="cut()" class="btn vote-btn btn-danger"><span id="vote4">{{ncuts || 0}} 人</span><br/><i class="icon-big-ban-circle"></i><br/>要求刪除</button></div></div></div></div></div><script>setTimeout(function() {',
'    initTreeMap();',
'}, 500);</script></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial4.html', [
'<div class="treemap-root"><div data-toggle="buttons-radio" class="btn-group"><a class="btn default active">Default</a><a class="btn bycat">政事別</a><a class="btn bytop">主管單位</a></div><div id="bubble-circle-size" class="btn">圖例</div><div id="bubble-info"><div id="bubble-info-inner"><i id="bubble-info-close" style="margin-top:-5px" class="icon-big-close"></i><div id="bubble-info-left"><div id="bubble-detail-info"><div id="bubble-detail-names"><i style="margin-top:-9px" class="icon-big-info-sign"></i><span id="bubble-detail-name">???</span>(<span id="bubble-detail-depname">???</span>)</div><div id="bubble-detail-amount"><span id="bubble-detail-amount-value">???</span><span id="bubble-detail-amount-quantifier"></span><span id="bubble-detail-amount-unit">元</span>(<span id="bubble-detail-amount-change">???</span>&nbsp;)<br/>( 即為<span id="bubble-detail-amount-alt">???</span>&nbsp;)<br/><div id="bubble-detail-amount-link"><span>連結到此項 :</span><a id="bubble-detail-link" href="view4">http://g0v.tw/view4</a></div></div></div><hr/><div id="bubble-detail-change-bar"></div><hr/><div id="budget-tagger"><div class="input-append"><input ng-model="tagname" size="13" type="text" placeholder="例如: 林益世" class="span2"/><button type="button" ng-click="addtag()" class="btn">標記相關人士</button></div><div id="budget-tags"><span ng-repeat="tag in tags" class="badge budget-tag"> ',
'{{tag}}  </span></div></div><hr/><div id="budget-vote"><div id="budget-vote-label"><span class="label">透過按一下表達你對於此預算的看法！</span></div><div id="BudgetItem" class="btn-toolbar"><div class="btn-group"><button ng-click="like()" class="btn vote-btn"><span id="vote1">{{nlikes || 0}} 人</span><br/><i class="icon-big-plus"></i><br/>希望追加</button><button ng-click="confuse()" class="btn vote-btn"><span id="vote2">{{nconfuses || 0}} 人</span><br/><i class="icon-big-question-sign"> </i><br/>表示不懂</button><button ng-click="hate()" class="btn vote-btn"><span id="vote3">{{nhates || 0}} 人</span><br/><i class="icon-big-minus"></i><br/>建議減少</button><button ng-click="cut()" class="btn vote-btn btn-danger"><span id="vote4">{{ncuts || 0}} 人</span><br/><i class="icon-big-ban-circle"></i><br/>要求刪除</button></div></div></div></div><div id="bubble-info-right"></div></div></div><div id="bubble-chart"></div><script>test_bubble();</script><svg><g><defs><radialGradient id="MyGradient" gradientUnits="userSpaceOnUse" cx="500" cy="350" r="500" fx="400" fy="200"><stop offset="0%" stop-color="red"></stop><stop offset="50%" stop-color="blue"></stop><stop offset="100%" stop-color="red"></stop></radialGradient></defs></g></svg></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/profile.html', [
'<div ng-controller="Profile"><h1>Hi, {{name}}</h1></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/tags.html', [
'<div id="budget-tagger"><div class="input-append"><input ng-model="tagname" size="13" type="text" placeholder="例如: 林益世" class="span2"/><button type="button" ng-click="addtag()" class="btn">標記相關人士</button></div><div id="budget-tags"><span ng-repeat="tag in tags" class="badge budget-tag"> ',
'{{tag}}  </span></div></div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/vote.html', [
'<div id="budget-vote"><div id="budget-vote-label"><span class="label">透過按一下表達你對於此預算的看法！</span></div><div id="BudgetItem" class="btn-toolbar"><div class="btn-group"><button ng-click="like()" class="btn vote-btn"><span id="vote1">{{nlikes || 0}} 人</span><br/><i class="icon-big-plus"></i><br/>希望追加</button><button ng-click="confuse()" class="btn vote-btn"><span id="vote2">{{nconfuses || 0}} 人</span><br/><i class="icon-big-question-sign"> </i><br/>表示不懂</button><button ng-click="hate()" class="btn vote-btn"><span id="vote3">{{nhates || 0}} 人</span><br/><i class="icon-big-minus"></i><br/>建議減少</button><button ng-click="cut()" class="btn vote-btn btn-danger"><span id="vote4">{{ncuts || 0}} 人</span><br/><i class="icon-big-ban-circle"></i><br/>要求刪除</button></div></div></div>',''].join("\n"));
}]);